### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wiseaidev** [brave-chat/brave-chat#14]
- [x] Send and receive images through WebSockets.
- [x] Add more notifications.
- [ ] Create an infrastructure using kubectl, minikube, docker and deployed it on one server...
- [ ] End-to-end encryption?
- [ ] Send Videos, PDFs ...
- [ ] Add user roles: admin, regular user.
- [ ] Create an admin dashboard
